version: '3'
services:
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=userservice
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

volumes:
  database-data: